---

- name: download Java7
  get_url:
  # url:  "http://download.oracle.com/otn/java/jdk/7u79-b15/jdk-7u79-linux-i586.rpm"
   url: "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-i586.rpm"
   headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
   validate_certs: no
   dest: /tmp/Java7.rpm
   mode: 0440


- name: Install Java 7
  yum:
   name: /tmp/Java7.rpm
